package com.ad.core.hope.service.admin;

import com.ad.core.hope.model.admin.SysRoleResource;
import java.util.List;

public interface SysRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    int insert(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    SysRoleResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    List<SysRoleResource> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    int updateByPrimaryKey(SysRoleResource record);
}