package com.ad.core.hope.model.admin;

import java.util.Date;

public class SysResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.resourceId
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private Integer resourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.uresource_uuid
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private String uresourceUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.name
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.description
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.url
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.type
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.priority
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.parent_id
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.parent_ids
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private String parentIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.permission
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.icon
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.available
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private Integer available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.create_time
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.update_time
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.resourceId
     *
     * @return the value of sys_resource.resourceId
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.resourceId
     *
     * @param resourceid the value for sys_resource.resourceId
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.uresource_uuid
     *
     * @return the value of sys_resource.uresource_uuid
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public String getUresourceUuid() {
        return uresourceUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.uresource_uuid
     *
     * @param uresourceUuid the value for sys_resource.uresource_uuid
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setUresourceUuid(String uresourceUuid) {
        this.uresourceUuid = uresourceUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.name
     *
     * @return the value of sys_resource.name
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.name
     *
     * @param name the value for sys_resource.name
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.description
     *
     * @return the value of sys_resource.description
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.description
     *
     * @param description the value for sys_resource.description
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.url
     *
     * @return the value of sys_resource.url
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.url
     *
     * @param url the value for sys_resource.url
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.type
     *
     * @return the value of sys_resource.type
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.type
     *
     * @param type the value for sys_resource.type
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.priority
     *
     * @return the value of sys_resource.priority
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.priority
     *
     * @param priority the value for sys_resource.priority
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.parent_id
     *
     * @return the value of sys_resource.parent_id
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.parent_id
     *
     * @param parentId the value for sys_resource.parent_id
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.parent_ids
     *
     * @return the value of sys_resource.parent_ids
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.parent_ids
     *
     * @param parentIds the value for sys_resource.parent_ids
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.permission
     *
     * @return the value of sys_resource.permission
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.permission
     *
     * @param permission the value for sys_resource.permission
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.icon
     *
     * @return the value of sys_resource.icon
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.icon
     *
     * @param icon the value for sys_resource.icon
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.available
     *
     * @return the value of sys_resource.available
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public Integer getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.available
     *
     * @param available the value for sys_resource.available
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setAvailable(Integer available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.create_time
     *
     * @return the value of sys_resource.create_time
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.create_time
     *
     * @param createTime the value for sys_resource.create_time
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.update_time
     *
     * @return the value of sys_resource.update_time
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.update_time
     *
     * @param updateTime the value for sys_resource.update_time
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}