package com.ad.core.hope.model.admin;

public class SysRoleResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.id
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.roleId
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.resourceId
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    private String resourceid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.id
     *
     * @return the value of sys_role_resource.id
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.id
     *
     * @param id the value for sys_role_resource.id
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.roleId
     *
     * @return the value of sys_role_resource.roleId
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.roleId
     *
     * @param roleid the value for sys_role_resource.roleId
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.resourceId
     *
     * @return the value of sys_role_resource.resourceId
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public String getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.resourceId
     *
     * @param resourceid the value for sys_role_resource.resourceId
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    public void setResourceid(String resourceid) {
        this.resourceid = resourceid;
    }
}