package com.ad.core.service;

import com.ad.core.model.SysRoleResource;
import java.util.List;

public interface SysRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Mon Jul 30 18:39:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Mon Jul 30 18:39:31 CST 2018
     */
    int insert(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Mon Jul 30 18:39:31 CST 2018
     */
    SysRoleResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Mon Jul 30 18:39:31 CST 2018
     */
    List<SysRoleResource> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated Mon Jul 30 18:39:31 CST 2018
     */
    int updateByPrimaryKey(SysRoleResource record);
}