package com.ad.core.hope.service.admin;

import com.ad.core.hope.model.admin.SysResource;
import java.util.List;

public interface SysResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    int deleteByPrimaryKey(Integer resourceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    int insert(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    SysResource selectByPrimaryKey(Integer resourceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    List<SysResource> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sun Aug 26 12:27:30 CST 2018
     */
    int updateByPrimaryKey(SysResource record);
}