package com.ad.core.model;

public class SysUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.id
     *
     * @mbggenerated Mon Jul 30 18:39:31 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.userId
     *
     * @mbggenerated Mon Jul 30 18:39:31 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.roleId
     *
     * @mbggenerated Mon Jul 30 18:39:31 CST 2018
     */
    private String roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.id
     *
     * @return the value of sys_user_role.id
     *
     * @mbggenerated Mon Jul 30 18:39:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.id
     *
     * @param id the value for sys_user_role.id
     *
     * @mbggenerated Mon Jul 30 18:39:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.userId
     *
     * @return the value of sys_user_role.userId
     *
     * @mbggenerated Mon Jul 30 18:39:31 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.userId
     *
     * @param userid the value for sys_user_role.userId
     *
     * @mbggenerated Mon Jul 30 18:39:31 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.roleId
     *
     * @return the value of sys_user_role.roleId
     *
     * @mbggenerated Mon Jul 30 18:39:31 CST 2018
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.roleId
     *
     * @param roleid the value for sys_user_role.roleId
     *
     * @mbggenerated Mon Jul 30 18:39:31 CST 2018
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }
}